.PHONY: generate
## Install tools
all:
#region CODE_REGION(project)
	go install github.com/onsi/ginkgo/v2/ginkgo@v2.12.0
	go install github.com/matryer/moq@v0.3.3
	go install github.com/git-chglog/git-chglog/cmd/git-chglog@v0.15.4
	go install golang.org/x/vuln/cmd/govulncheck@v1.0.1
	go install github.com/abice/go-enum@v0.5.8
#endregion
#region CODE_REGION(service)
#endregion